apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://raw.githubusercontent.com/tektoncd/catalog/main/task/npm/0.1/npm.yaml
- build-bot.ServiceAccount.yaml
- create-configuration.Task.yaml
- deploy.Task.yaml
- git-credentials.Secret.yaml
- next.Pipeline.yaml
- quay.Secret.yaml
- webhook-receiver.EventListener.yaml
- production-repository.ConfigMap.yaml
- save-configuration.Task.yaml
